# Generated by Django 2.2.4 on 2019-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name=models.Model)),
                ('dept_name', models.CharField(max_length=40, unique=True, verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False, verbose_name=models.Model)),
                ('birth_date', models.DateField(max_length=200, verbose_name=models.Model)),
                ('first_name', models.CharField(max_length=14, verbose_name=models.Model)),
                ('last_name', models.CharField(max_length=16, verbose_name=models.Model)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', '"Female"')], default='M', max_length=1, verbose_name=models.Model)),
                ('hire_date', models.DateField(max_length=15, verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=models.Model)),
                ('from_date', models.DateField(max_length=20, verbose_name=models.Model)),
                ('to_date', models.DateField(blank=True, max_length=20, null=True, verbose_name=models.Model)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name=models.Model)),
                ('from_date', models.DateField(max_length=20, verbose_name=models.Model)),
                ('to_date', models.DateField(max_length=20, verbose_name=models.Model)),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Dept_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(max_length=20, verbose_name=models.Model)),
                ('to_date', models.DateField(max_length=20, verbose_name=models.Model)),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Departments')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees')),
            ],
        ),
    ]
